import type { Post } from '@/types';

/**
 * Static posts from the RCT "posts rct" folder.
 * Sorted by date descending (newest first).
 */
export const rctPosts: Post[] = [
  {
    id: 'rct-post-9',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `Same passion. Same pace. Same smiles.\nBizerte x Tunis 🌿\n#runningclubbizerte #runningclubtunis #runningclublamarsa #runningclubmannouba`,
    image: '/posts-rct/post 9/img.png',
    likes: [],
    comments: [],
    createdAt: '2026-01-25T12:00:00.000Z',
    type: 'post',
  },
  {
    id: 'rct-post-8',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `@running_club_tunis more than a running club 🫶🏃‍♀️`,
    video: '/posts-rct/post 8/video.mp4',
    likes: [],
    comments: [],
    createdAt: '2026-01-23T12:00:00.000Z',
    type: 'reel',
  },
  {
    id: 'rct-post-7',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `يتمنى نادي العدو بتونس لكل أعضاءه عيد إضحى مبارك🕌🐏☪️`,
    image: '/posts-rct/post 7/img.png',
    likes: [],
    comments: [],
    createdAt: '2025-06-05T12:00:00.000Z',
    type: 'post',
  },
  {
    id: 'rct-post-6',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `🏃‍♂️ COUREZ POUR UNE CAUSE, COURIR POUR DES VIES ! 🏃‍♀️\n\nRejoignez le mouvement RUN OF HEROES avec notre tee-shirt solidaire conçu pour les vrais battants 💪\n\n📞 Commandez au : 55 573 141 — Tailles S M L XL (XXL sur commande)\n\n#RunOfHeroes #atGmo #SolidaritéEnMouvement`,
    images: [
      '/posts-rct/post 6/img1.jpg',
      '/posts-rct/post 6/img2.jpg',
      '/posts-rct/post 6/img3.jpg',
      '/posts-rct/post 6/img4.jpg',
      '/posts-rct/post 6/img5.jpg',
      '/posts-rct/post 6/img6.jpg',
      '/posts-rct/post 6/img7.jpg',
      '/posts-rct/post 6/img8.jpg',
      '/posts-rct/post 6/img9.jpg',
    ],
    likes: [],
    comments: [],
    createdAt: '2025-09-02T12:00:00.000Z',
    type: 'post',
  },
  {
    id: 'rct-post-5',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `🏃‍♂️ COUREZ POUR UNE CAUSE, COURIR POUR DES VIES ! 🏃‍♀️\n\nRejoignez le mouvement RUN OF HEROES avec notre tee-shirt solidaire conçu pour les vrais battants 💪\n\n📞 Commandez au : 55 573 141 — Tailles S M L XL (XXL sur commande)\n\n#RunOfHeroes #atGmo #SolidaritéEnMouvement #RunningAvecUnBut #CourirPourGuérir`,
    image: '/posts-rct/post 5/img.png',
    likes: [],
    comments: [],
    createdAt: '2025-05-20T12:00:00.000Z',
    type: 'post',
  },
  {
    id: 'rct-post-4',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `إجري للخير❤️مرحبا🎉`,
    image: '/posts-rct/post 4/img.png',
    likes: [],
    comments: [],
    createdAt: '2025-04-21T12:00:00.000Z',
    type: 'post',
  },
  {
    id: 'rct-post-3',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `L'association TAHEC, en collaboration avec le Running Club Tunis et OUTDOOR EVENTS, organise la première édition du Triathlon Ecologique « Hergla X-Tri ».\n\nCet événement est un cross-triathlon et duathlon courte distance. Ouvert aux triathlètes et aux passionnés de fitness de tous âges et de tous niveaux.\n\nDeux épreuves au programme:\n- Cross-Triathlon S (750m Nage – 20km VTT – 5km Urban Trail)\n- Cross-Duathlon (2.5km Urban Trail – 20km VTT – 2.5km Urban Trail)\n\nPour plus d'infos: Info@outdoorevents.tn / +216 25 842 756`,
    image: '/posts-rct/post 3/img.png',
    likes: [],
    comments: [],
    createdAt: '2025-04-04T12:00:00.000Z',
    type: 'post',
  },
  {
    id: 'rct-post-2',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `تقبل الله منا ومنكم صالح الأعمال. تتمنى لكم مجموعتنا عيد فطر مبارك سعيد. 🌙📿🕌`,
    image: '/posts-rct/post 2/img.png',
    likes: [],
    comments: [],
    createdAt: '2025-03-30T12:00:00.000Z',
    type: 'post',
  },
  {
    id: 'rct-post-1',
    authorId: 'rct',
    authorName: 'Running Club Tunis',
    authorAvatar: '',
    content: `Rejoignez-nous pendant le mois saint de ramadan pour nos runs avant iftar les mardis, jeudis, et dimanches. #رمضان_كريم`,
    image: '/posts-rct/post 1/img.png',
    likes: [],
    comments: [],
    createdAt: '2025-02-25T12:00:00.000Z',
    type: 'post',
  },
];
